[test]
coveragePathIgnorePatterns = [
  "bin/main.ts",
  "../application/**",
  "../domain/**",
  "../event-sourcing/**",
  "../test-support/**",
]
coverageSkipTestFiles = true
coverageThreshold = 1.0
